
auth.token=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

defaults.org=antoine-sauray
defaults.project=boncowork-mobile

defaults.url=https://sentry.io/
