# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(build_number: 30, xcodeproj: "BonCowork.xcodeproj")
    build_app(workspace: "BonCowork.xcworkspace", scheme: "BonCowork")
    api_key = app_store_connect_api_key(
      key_id: "VN43KR9NS9",
      issuer_id: "3709c9d4-5d9d-473a-88cc-0c828c639dc4",
      key_filepath: "../AuthKey_VN43KR9NS9.p8"
    )
    upload_to_testflight(
      api_key: api_key
    )
  end
end
